name: Automation Workflow for GitHub Projects

on:
  issues:
    types:
      - opened
      - assigned
      - closed
  pull_request:
    types:
      - opened
      - closed

jobs:
  project_automation:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up GitHub CLI
      - name: Install GitHub CLI
        run: sudo apt install gh -y

      # Add the issue to "Backlog" when created
      - name: Add issue to Backlog
        if: github.event_name == 'issues' && github.event.action == 'opened'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ITEM_ID=$(gh issue view ${{ github.event.issue.number }} --format json id -q ".id")
          BACKLOG_COLUMN_ID=$(gh project field-list 2 --owner chriscedrick --format json name,id -q '.[] | select(.name == "Backlog") | .id')
          gh project item add 2 --item-id $ITEM_ID --owner chriscedrick

      # Move to "In progress" when assigned
      - name: Move issue to "In progress" when assigned
        if: github.event_name == 'issues' && github.event.action == 'assigned'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ITEM_ID=$(gh issue view ${{ github.event.issue.number }} --format json id -q ".id")
          IN_PROGRESS_FIELD_ID=$(gh project field-list 2 --owner chriscedrick --format json name,id -q '.[] | select(.name == "In progress") | .id')
          gh project item-field-update 2 --item-id $ITEM_ID --field-id $IN_PROGRESS_FIELD_ID --value "In progress" --owner chriscedrick

      # Move to "Done" when the issue is closed
      - name: Move issue to "Done"
        if: github.event_name == 'issues' && github.event.action == 'closed'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ITEM_ID=$(gh issue view ${{ github.event.issue.number }} --format json id -q ".id")
          DONE_FIELD_ID=$(gh project field-list 2 --owner chriscedrick --format json name,id -q '.[] | select(.name == "Done") | .id')
          gh project item-field-update 2 --item-id $ITEM_ID --field-id $DONE_FIELD_ID --value "Done" --owner chriscedrick

      # Add PR to "In review" when created
      - name: Add PR to "In review"
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ITEM_ID=$(gh pr view ${{ github.event.pull_request.number }} --format json id -q ".id")
          IN_REVIEW_FIELD_ID=$(gh project field-list 2 --owner chriscedrick --format json name,id -q '.[] | select(.name == "In review") | .id')
          gh project item add 2 --item-id $ITEM_ID --owner chriscedrick

      # Move PR to "Done" when merged
      - name: Move PR to "Done"
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ITEM_ID=$(gh pr view ${{ github.event.pull_request.number }} --format json id -q ".id")
          DONE_FIELD_ID=$(gh project field-list 2 --owner chriscedrick --format json name,id -q '.[] | select(.name == "Done") | .id')
          gh project item-field-update 2 --item-id $ITEM_ID --field-id $DONE_FIELD_ID --value "Done" --owner chriscedrick
